# Where logs are stored
log_path: ../../nvr/logs

# Location of ffmpeg binary
ffmpeg_binary: ffmpeg # or full path: /usr/bin/ffmpeg

# Stream settings
stream:
  segment_seconds: 300 # 5 minutes per file
  output_path: ../../nvr/streams
  retention_days: 0.1 # backup files older than this many days (can be a partial day too)
  backup_retention_days: 5
  backup_output_path: ../../nvr/streams/backup

cameras:
  - id: driveway
    name: driveway
    enabled: true
    log_ffmpeg: false
    rtsp_url: rtsp://{RTSP_USER}:{RTSP_PASSWORD}@camera-driveway.lan/Streaming/Channels/101/

  - id: garage
    name: garage
    enabled: true
    log_ffmpeg: false
    rtsp_url: rtsp://{RTSP_USER}:{RTSP_PASSWORD}@camera-garage.lan/Streaming/Channels/101/

  - id: front_yard
    name: front_yard
    enabled: true
    log_ffmpeg: false
    rtsp_url: rtsp://{RTSP_USER}:{RTSP_PASSWORD}@camera-front-right.lan/Streaming/Channels/101/
